### ISSUE TITLE
Deprecation Warning on collections import in _collections.py

### ISSUE THREAD

**Issue by csabella** [shazow/urllib3#1324]
/pip/_vendor/requests/packages/urllib3/_collections.py:2: 
DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  from collections import Mapping, MutableMapping

**Comment by haikuginger** [comment]
@csabella, is this in the Python 3.7 beta?

**Comment by csabella** [comment]
@haikuginger   Yes, sorry.  I created a venv under the 3.7 beta and got the message when using pip.

**Comment by haikuginger** [comment]
Okay, let's get this fixed up for 3.8 before we officially add support for 3.7. I recommend the following construct:

```python
try:
    from collections.abc import Mapping, MutableMapping
except ImportError:
    from collections import Mapping, MutableMapping

Another option would be to wait for `six` to add a `moves` item for `collections.abc` and use that, combining it with an upgrade of `six` to whatever version includes that. However, we don't want to wait too long, because we'll want official support for 3.7 as soon as it releases.

**Comment by haikuginger** [comment]
Fixed in #1325.

**Comment by Ch3ck** [comment]
@haikuginger has this issue been fixed yet? I still get the same errors for Python 3.7 or is there a getaround for this in Py3
